### ISSUE TITLE
DK_timerev broken

### ISSUE THREAD

**Issue by Philiphorst** [benfulcher/hctsa#18]
DK_timerev function seems to be broken. 
The function call to DK_timeLagembed in DK_timerev has been renamed, but the function DK_lagembed has not been renamed to DK_timeLagembed.

**Comment by benfulcher** [comment]
Thanks for picking this up! It's already fixed in the OperationChanges branch but haven't merged to master yet. Will do in the next few days :)

**Comment by benfulcher** [comment]
Merged in the latest version, https://github.com/benfulcher/hctsa/releases/tag/v0.94
