### ISSUE TITLE
Is there any getting started documentation ?

### ISSUE THREAD

**Issue by faturita** [benfulcher/hctsa#19]
This is not an issue, but I couldn't find a 'getting started' page with information on how to execute the TS_Init on a given dataset.  Is any information on how to create the INP_test_ts.mat file manually ?

Thanks for the package and all the information, btw.  Great and amazing work !

**Comment by benfulcher** [comment]
Hi @faturita,
Thanks for the positive feedback, and for your question.
There is comprehensive documentation on [gitbook](https://www.gitbook.com/book/benfulcher/highly-comparative-time-series-analysis-manual/details)
I tried putting a bunch of book emojis on in the readme to draw attention to this, but maybe it's still not prominent enough...?
Good luck and do let me know how you go (and leave feedback here, or through comments in the gitbook docs) :)
