### ISSUE TITLE
Re: Forecasting

### ISSUE THREAD

**Issue by xenmind** [benfulcher/hctsa#33]
Hi,

I'm generating features for a forecasting application. I require "causal" features, i.e. features that at any point in time do not use future information. I noted that there is a subset of features with the keyword 'forecasting.' Are these all causal? Are any features in other subsets also causal? Is there a simple way to extract only those sorts of features?

Thanks for any help on this matter,
Gavin.

**Comment by benfulcher** [comment]
Hi Gavin,
All features implemented in _hctsa_ take in a time series and output a feature that is a summary statistic of the dynamics in that time series. You can restrict the time window and put that restricted time series into hctsa to get features of the dynamics in that restricted time period (e.g., cutting out future time points).
All features labeled as 'forecasting' try to quantify the predictability of the time series by fitting, running, and evaluating the performance of several types of forecasting algorithms
Ben

**Comment by xenmind** [comment]
Ok, so I could apply hctsa to a rolling window of a time series and save the summary stat for each window to avoid future leaks. Really looking forward to testing hctsa out. Thank you.

**Comment by benfulcher** [comment]
Yeah, this is kind of like 'feature-based forecasting' (is there some property of the dynamics in the current time window that is informative of some future behavior of the time series.
I describe it briefly here: https://arxiv.org/abs/1709.08055
FYI, you may want to test the idea using a small, fast-to-compute feature set: https://github.com/chlubba/catch22
