### ISSUE TITLE
Matlab freezes

### ISSUE THREAD

**Issue by Adblu** [benfulcher/hctsa#37]
The problem I have is the following:

The code is: 
```
set_false_flag()
_ = hctsa.prepare()     # Here Matlab freezes
elevation_data = get_data()
features_data = get_features(elevation_data)
save_data(features_data)
set_true_flag()
print "Done"
```

this code is packed into a method and repeated in a loop ~20000 times.
The problem is that on 14 iteration Matlab for some reason freezes.

Those are the log messages.
```
Starting engine
Warming up
Configuring HCTSA
Setting up HCTSA operators        (STUCK AT THIS PLACE)
Hooray, we can use HCTSA now...  
```

How I can solve it ? 
Maybe running it in a loop so many times is a bad idea ?!
Is is possible to set up Matlab running one globally and then use its functions ?

**Comment by benfulcher** [comment]
This isn't an issue with the hctsa software, but with a piece of linkage software, right…?
Is this [pyopy](https://github.com/strawlab/pyopy)? Perhaps you can start an issue there, but it doesn't seem to be in active development…

**Comment by Adblu** [comment]
You are right. Thank you.
