### ISSUE TITLE
Feature computed separately different from TS_DataMat

### ISSUE THREAD

**Issue by AvisP** [benfulcher/hctsa#42]
I used HCTSA on a particular dataset and was trying to analyze a particular feature i.e. SP_Summaries_fft_mean. When I am comparing the results in the TS_DataMat column and a code ran on the same dataset separately eg. [out] = SP_Summaries(TimeSeries(1).Data,'fft',[],[],false); I found that the two values are different for out.mean. I am looking at column 4534 in TS_DataMat as from Operations variable that seems to be corresponding feature. Kindly assist.

**Comment by benfulcher** [comment]
Hi @AvisP thanks for the issue—this feature operates on the z-scored time series, so you will need to run `SP_Summaries(zscore(TimeSeries(1).Data),'fft',[],[],false)`. _hctsa_ uses the convention of `y` for a _z_-scoring of the input time series, e.g., in lines of `INP_mops.txt`:  `SP_Summaries(y,'fft',[],[],false)`. Perhaps a clearer notation would be `x_z` to emphasize this transformation. I will implement this for clarity when I'm able. Hope this helps.
