### ISSUE TITLE
Warning: No available confusion matrix plotting functions 

### ISSUE THREAD

**Issue by LJGz** [benfulcher/hctsa#53]
Using TS_Classify(mynormalizedfile) with two classes accuracy is calculated in the command output then:
```
Warning: No available confusion matrix plotting functions 
> In TS_Classify (line 233) 
```
And no classification plot is generated. 
I installed Matlab 2020a and ensured I have the Stats/ML Toolbox installed and the Deep Learning Toolbox. Still get the same error.

Tested with latest version of all files.

**Comment by benfulcher** [comment]
Thanks @LJGz You're right—this is now fixed in 3ec5b13a1d2994442d811fa199a8279bc1a1e768
If you pull from the master branch, this should work 👍
