### ISSUE TITLE
Wrong_TS_Classify

### ISSUE THREAD

**Issue by ozone521** [benfulcher/hctsa#55]
Hi Ben,

I have been using your HCTSA toolbox for sometime and had a question. HCTSA is an outstanding job.
When I  get start with "hctsa_phenotypingWorm-master" and "hctsa_phenotypingFly-master" project. Here was the question that
`plotconfusion(realLabels,predictLabels);`
`plotconfusion (line 111)     update_args = standard_args(args{:});`
`plotconfusion>standard_args (line 255) Value is not a matrix or cell array.`
I did not understand how to solve this problem. Can you give me some suggestions?

**Comment by benfulcher** [comment]
Thanks @ozone521 for your feedback. Please help me reproduce with details of what code you ran.
Look also within the lines around where `plotconfusion` is run—there are different versions of confusion matrix plotting in different versions of matlab. Would appreciate if you could find what is being toggled on your version of Matlab

**Comment by ozone521** [comment]
Hi Ben,
Thank you for your prompt reply. It is indeed a problem caused by different versions of MATLAB. When I used the MATLAB R2020a software, this problem was solved.

**Comment by benfulcher** [comment]
Thanks @ozone521 I wonder how I could add a `if` statement to catch the error you found from a previous Matlab version… Anyway, glad you were able to resolve with an update. Good luck with your research
