### ISSUE TITLE
Error when running TS_LocalClearRemove

### ISSUE THREAD

**Issue by jstan15** [benfulcher/hctsa#57]
Hi,

I tried to run this code from the documentation (https://hctsa-users.gitbook.io/hctsa-manual/setup/compiling_binaries) to ignore the TISEAN functions

`TS_LocalClearRemove('ops',TS_GetIDs('tisean','raw','ops'),1,'raw');`

However this produces an error:

`TS_LocalClearRemove('ops',TS_GetIDs('tisean','raw','ops'),1,'raw');`
`Loading data from HCTSA.mat... Done.`
`Warning: No matches to 'tisean' found in HCTSA.mat `
`> In TS_GetIDs (line 105) `
`Error: File: TS_LocalClearRemove_2.m Line: 1 Column: 31`
`"@" dotted names can be used only within a CLASS block.`

After editing the first line of the TS_LocalClearRemove.m file from:

`function TS_LocalClearRemove.m(whatData,tsOrOps,idRange,doRemove)`

to:

`function TS_LocalClearRemove(tsOrOps,idRange,doRemove,whatData)`

The error appears to be fixed and I am able to ignore the TISEAN functions now. I don't know whether this change would affect anything else, because I had just downloaded the library today, but at least it appears to solve this problem that I'm facing.

Thank you for all your hard work in providing us with this library!
JeiShian

**Comment by benfulcher** [comment]
Thanks @jstan15 for your interest in this package, and thoughtfully described issue.
I've fixed this weird typo with the `.m` in the function name in `TS_LocalClearRemove` in a new [commit](https://github.com/benfulcher/hctsa/commit/9ee095600706ff8cc3f3ef6ab2ddb085a8e4f4e4) to master, and also updated the relevant syntax in the gitbook to reflect the new order of inputs.
Thanks again, and good luck with your use of _hctsa_! Feedback always welcome :)
