### ISSUE TITLE
Multichannel EEG analysis

### ISSUE THREAD

**Issue by Hyungjujin** [benfulcher/hctsa#58]
Dear Ben,

Thank you so much for developing such a great tool. I’m a pre-med student and I’m trying to analyse multi-channel EEG data with your program, but I’ve encountered a problem while doing so.

Since I’m trying to analyse multi-channel EEG data, I have more than one time series for each subject. However, when I read your journals and gitbook, it said that HCTSA can only analyse one time-series data for a subject. Could you kindly guide me on how to analyse multi-channel EEG data using HCTSA if it is possible?

Thank you.

Yours sincerely,
HJ

**Comment by benfulcher** [comment]
Hi HJ,

No worries and thanks for your interest in our work. _hctsa_ is a comprehensive library of univariate time-series features. I give some generic advice on adapting it to multivariate systems on the [wiki](https://github.com/benfulcher/hctsa/wiki/FAQs). If you have further questions about your application, happy to discuss specific issues by email.
Hope this helps!,

Ben
