### ISSUE TITLE
nn_prepare.m as a function is not supported and a whole host of other errors

### ISSUE THREAD

**Issue by posttenebre** [benfulcher/hctsa#60]
I am using Ethoscope velocity data to distinguish between genotype. I don't have a license for the econometrics toolbox so I get a few errors about that. Additionally I get errors about functions not being supported. Are these issue with my installation or is it because the data is not amenable to that particular analysis?

```
Execution of script nn_prepare as a function is not supported:
/home/luca/Toolboxes/OpenTSTOOL/tstoolbox/mex/nn_prepare.m
```

**Comment by benfulcher** [comment]
Can you let me know what platform and what version of Matlab you are using? Can you also let me know how this error emerges? It's possible the mex files didn't compile properly… (`compile_mex`)

**Comment by posttenebre** [comment]
MATLAB R2021a
Ubuntu 20.10 x86_64
5.8.0-50-generic
AMD Ryzen 9 3900X
gcc version 10.2.0

The errors show up when running:
`TS_Init('data.mat')`
`TS_Compute(true)`

**Comment by benfulcher** [comment]
How did the `install` script go? Did you successfully `compile_mex`?

**Comment by posttenebre** [comment]
Here is the pastebin for the install 
https://pastebin.com/yRhwY7vz

**Comment by benfulcher** [comment]
Yeah it seems that the TSTOOL package is messing you up. Your compiler is also surprisingly having issues with some of catch22 (but this won't bother you)… I wonder if this is something to be more generally aware of with gcc 10.
To be honest, the TSTOOL package it not in active development so any issues related to this package are unlikely to be fixed. The TSTOOL-based features are in my experience, not very high quality—they should probably be removed from _hctsa_ in a future release.
Is this preventing you from running your analysis, or is it just preventing you from using TSTOOL-based features? You could either remove the problem features from your list if the error messages bother you, or they will just be filtered out after the computation (at the `TS_Normalize` step).

**Comment by posttenebre** [comment]
I am able to complete the run of computation and then use the HCTSA.mat for analysis. At the moment I am wondering how much is missing in terms of analysis without some of these features and the econometrics toolbox.

**Comment by benfulcher** [comment]
From my experience, the TSTOOL features are non-essential, and of course it depends on your application, but I suspect losing the econometric toolbox features should also be fine—you will still have a large and diverse feature set to work with.
FYI: I typically recommend working up your pipeline using [catch22](https://github.com/chlubba/catch22) to avoid the computational costs, and you can always repeat later with the full feature set.

**Comment by posttenebre** [comment]
Thank you for you suggestion, I will using the catch22 sets and work my way up.
