### ISSUE TITLE
Not able to skip User input "y" in TS_Init

### ISSUE THREAD

**Issue by javanray** [benfulcher/hctsa#62]
Hi,

I am trying to extract the temporal features from a large number of BOLD resting state fMRI signals using hctsa toolbox. Therefore, I have written a script which loads keyword matrices, labels, and timeseries in a loop and inputs them sequentially to TS_Init for creation of HCTSA.mat files. But, for each loop the algorithm requires a user input "y" to confirm the time series. I could not find the corresponding line of the code in "TS_Init.m" file of the toolbox to modify it and skip this step, and I was wondering if you could please guide me towards solving this issue.

Thank you for the great toolbox.
Regards,
Ali

**Comment by benfulcher** [comment]
Hi Ali,

In general, a good idea to get the information into a single set of keywords, labels, … and then run a single TS_Init, but I guess you have a more specific use case.
The `beVocal` flag (4th input to `TS_Init` is the one to edit). Setting to `[false,false,false]` should disable user input for all three: time series, master operations, and operations.

Ben

**Comment by javanray** [comment]
Fantastic, thank you very much for your quick and exact reply, it worked perfectly!  Meanwhile, regarding your suggestion of using a single set of keywords and lebels, I am working with a dataset containing 646 subjects which we have extracted 400 timeseries per subject each corresponding to one of the 400 Schafer atlas brain regions). I am used a single set of 400 labels for all subjects' time series (each region has it's own label), but for the keywords I used a unique keyword (represantative of the corresponding subject ID and region) for each timeseries.
If you have any recommendations or suggestions regarding the use of labels and keywords, I would be more than happy to hear them. 

Thank you,
Ali

**Comment by benfulcher** [comment]
No worries. Yep, it's up to you whether to make a different HCTSA file for each subject (TS_Init), or combine them all into a single input file, and label each according to both a subject and a region ID (one big HCTSA file). I would suggest the latter, and I would also suggest starting with a reduced feature set (e.g., catch22), before scaling up to hctsa (so you can work through the analyses before taking on the computational expense of the hctsa feature set). Good luck.
