### ISSUE TITLE
Init only with notLengthDependent features

### ISSUE THREAD

**Issue by Drodriguez-9** [benfulcher/hctsa#63]
Hi Ben, first of all thanks for this amazing tool.
Could you please explain me how to compute only the notLengthDependent features? In your tutorial it's only explained how to do so with the catch22 set. 
Thank you.

**Comment by benfulcher** [comment]
Thanks @Drodriguez-9,
Easiest is to do a `TS_Init` with all features as `HCTSA.mat`, and then subset:
```matlab
[IDs_lenDep,IDs_notLenDep] = TS_GetIDs('lengthDependent','HCTSA.mat','ops','Keywords');
TS_Subset('HCTSA.mat',[],IDs_notLenDep,true,'HCTSA_lenDepFiltered.mat')
```
Then you have the full set initialized as `HCTSA.mat` and the length-dependent-removed as `HCTSA_lenDepFiltered.mat`. You can then e.g., just work from the lenDepFiltered version for the subsequent calculation.

I typically compute everything and then subset later for flexibility. If you go this route, then the `TS_Subset` is the command you use, just on the already-computed version of `HCTSA.mat`, or there is some capability for filtering for analysis without needing to create lots of filtered .mat files (e.g., in the `reducedFeatureSet` field of the classification parameter structure, cf. `GiveMeDefaultClassificationParams`).

Hope this helps and good luck with your research.
Ben
