### ISSUE TITLE
calling hctsa from python with matlab engine

### ISSUE THREAD

**Issue by Ziaeemehr** [benfulcher/hctsa#64]
Hello and thank you for sharing the great package,
Is it possible to call the package from python using the Matlab engine and if yes
do you have any instructions for that? 

best

**Comment by benfulcher** [comment]
Thanks @Ziaeemehr,
There is the [`pyopy`](https://github.com/strawlab/pyopy) package, but it's quite old and I'm not sure if it still works…
You can see more related resources on the [wiki](https://github.com/benfulcher/hctsa/wiki/Related-time-series-resources).
For _hctsa_, I would suggest that doing the feature extraction in Matlab, and outputting to csv (e.g., using the `OutputToCSV.m` file), and then continuing your analysis externally.
Or you can try an alternative feature extraction process natively in python (e.g., trialing an analysis in python using [catch22](https://github.com/chlubba/catch22)).
Hope this helps,
Ben

**Comment by benfulcher** [comment]
(cf. also this port of some of the hctsa functionality to python: https://github.com/fairscape/hctsa-py)
