### ISSUE TITLE
Typo in TS_Classify and errors running 'simpleNull' = false in ComputeCVAccuracies?

### ISSUE THREAD

**Issue by NeilwBailey** [benfulcher/hctsa#66]
I think there is a typo in TS_Classify, line 194 states:

assert(cfnParms.computePerFold == false);

I think it should be:

assert(cfnParams.computePerFold == false); ???

I'm also trying to run an analysis without using the simpleNull (because my classes are imbalanced). 

I was getting an error that: 

"Output argument "inSampleAccStd" (and possibly others) not assigned a value in the execution with "ComputeCVAccuracies" function."

So I added the following to the end of the ComputeCVAccuracies function:

if ~cfnParams.computePerFold
    inSampleAccStd = 0;
end

Then I got the following error:

Unrecognized function or variable 'inSampleAccStd'.

Error in ComputeCVAccuracies (line 49)
    inSampleAccStd = mean(inSampleAccStd,1);

Error in TS_Classify (line 203)
                nullStats(i) = ComputeCVAccuracies(TS_DataMat,shuffledLabels,cfnParams,true);

Which I think I have fixed by replacing line 49 in ComputeCVAccuracies with:

if cfnParams.computePerFold
        inSampleAccStd = mean(inSampleAccStd,1);
end

Hopefully these are accurate solutions!

Kind regards,

Neil

**Comment by benfulcher** [comment]
Thanks for picking up the `TS_Classify` typo—fixed. I've also tried to fix the others. See 64bf5f93b15d4ea3501b7f4fcc816ec070480c36
