### ISSUE TITLE
Multichannel EEG signal analysis

### ISSUE THREAD

**Issue by shivam-199** [benfulcher/hctsa#69]
Dear ben,

I am in the process of analyzing my 64-channel EEG recordings with HCTSA. However, I get the error that "each element of timeSeriesData must be univariate." I looked at the Bonn EEG dataset in the example and realized the data in that was univariate. What do you suggest for EEG signal analysis?

**Comment by benfulcher** [comment]
No software package is plug-and-play—you will have to think about a suitable way of framing the problem in a way that feature extraction makes sense.
Some generic tips for multivariate time series are on the FAQ: https://github.com/benfulcher/hctsa/wiki/FAQs#can-i-perform-a-multivariate-time-series-analysis-using-hctsa
You may wish to check out our recent pyspi. Good luck!
