### ISSUE TITLE
parallel operation

### ISSUE THREAD

**Issue by rmzargar** [benfulcher/hctsa#73]
**Hi** 
**I am running the computations with the parallel option on (TS_Compute(true);). but I receive this message:** 

>> TS_Compute(true);
Loading data from HCTSA.mat... Done.
Computation will be performed across multiple cores using Matlab's Parallel Computing Toolbox.
[26-Mar-2023 11:53:47]: Extracting 7752 features from each of 24 time series.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
; ; ; : : : : ; ; ;    26-Mar-2023 11:53:47     ; ; ; : : : ; ; ;
---------------Time series 1 / 24 - - - - - - - - - - -
Computations will be performed serially without parallelization.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Preparing to calculate N1
ts_id = 1, N = 50000 samples
Computing 7752 features.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**why the computation does not perform with parallelization?**

**Comment by benfulcher** [comment]
I can't see how this would happen without giving you a warning or explanation as to why it couldn't start a parallel session. I notice you closed it as completed—did you find anything that needs a fix or could more clearly give an appropriate message to the user?
[p.s. with 50000 samples in your time series, some of the hctsa features may be very slow… You may wish to downsample/subsample and/or start with the _catch22_ feature set]

**Comment by rmzargar** [comment]
It warned me that I did not install the parallel computation toolbox after
I ran the program for the second time. It is OK now. thank you.
